apiVersion: v1
kind: Service
metadata:
  name: vellozap-food
  namespace: vellozap-food
  labels:
    app.kubernetes.io/name: vellozap-food
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: arcobatrox
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vellozap-food
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
